package com.example.pos_kasir_app.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Kas(
    @SerialName("kas_id") val kasId: String? = null, // UUID generated by Supabase, nullable for inserts
    @SerialName("nama_kas") val namaKas: String,
    @SerialName("saldo_kas") val saldoKas: Double,
    @SerialName("keterangan_kas") val keteranganKas: String? = null,
    @SerialName("is_active") val isActive: Boolean = true,
    @SerialName("created_at") val createdAt: String? = null // Optional if handled by DB default
)